server:
  port: 8083
spring:
  application:
    name: user-info-service

#database connectivity
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update

# keycloak configuration

keycloak:
  realm: FMS-realm
  auth-server-url: http://localhost:8080
  resource: user-info-service
  public-client: true